apiVersion: v1
kind: Service
metadata:
  name: docker-k8s-cicd
  labels:
    app: docker-k8s-cicd
spec:
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app: docker-k8s-cicd
  type: NodePort
  